### ISSUE TITLE
Debuda hang analysis failed to detect that stream is missing tiles

### ISSUE THREAD

**Issue by tt-dcvijetic** [tenstorrent/tt-exalens#9]
Netlist (provided below) used to hang with pipegen2. When we ran debuda's hang analysis command it said `No issues detected`, however one of the multicast streams was missing 12 tiles. `tt-script` was able to tell that some streams have not gone idle. Can you take a look at why debuda missed this?

<details><summary>Click here to expand netlist</summary>

```
# test_config_id=$TEMPLATE_test_config_id
devices:
  arch: wormhole_b0

queues:
  input0_dram:
    type: queue
    input: HOST
    entries: 2
    grid_size: [1, 3]
    t: 1
    mblock: [54, 4]
    ublock: [1, 3]
    df: Float16
    ublock_order: r
    target_device: 0
    loc: dram
    dram: [[4, 0x10000000], [4, 0x10292220], [4, 0x10524440]]

  input1_dram:
    type: queue
    input: HOST
    entries: 2
    grid_size: [2, 6]
    t: 36
    mblock: [1, 2]
    ublock: [1, 1]
    df: Float16
    target_device: 0
    loc: dram
    dram: [[1, 0x10000000], [1, 0x10049220], [1, 0x10092440], [1, 0x100db660], [1, 0x10124880], [1, 0x1016daa0], [1, 0x101b6cc0], [1, 0x101ffee0], [1, 0x10249100], [1, 0x10292320], [1, 0x102db540], [1, 0x10324760]]

  output0_dram:
    type: queue
    input: op0
    entries: 2
    grid_size: [3, 2]
    t: 18
    mblock: [2, 6]
    ublock: [3, 2]
    df: Float16
    target_device: 0
    loc: dram
    dram: [[5, 0x10000000], [5, 0x10524420], [5, 0x10a48840], [5, 0x10f6cc60], [5, 0x11491080], [5, 0x119b54a0]]

  output1_dram:
    type: queue
    input: op1
    entries: 2
    grid_size: [3, 2]
    t: 36
    mblock: [6, 1]
    ublock: [1, 6]
    df: Float16
    target_device: 0
    loc: dram
    dram: [[0, 0x10000000], [0, 0x10524420], [0, 0x10a48840], [0, 0x10f6cc60], [0, 0x11491080], [0, 0x119b54a0]]

graphs:
  test_multi_tm_datacopy_matmul:
    target_device: 0
    input_count: 2
    feeder0:
      type: datacopy
      grid_loc: [0, 1]
      grid_size: [6, 2]
      inputs: [input0_dram]
      in_df: [Float16]
      acc_df: Float16
      out_df: Float16
      intermed_df: Float16
      ublock_order: c
      buf_size_mb: 2
      math_fidelity: HiFi4
      t: 1
      mblock: [9, 3]
      ublock: [1, 6]
    feeder1:
      type: datacopy
      grid_loc: [8, 0]
      grid_size: [1, 2]
      inputs: [input1_dram]
      in_df: [Float16]
      acc_df: Float16
      out_df: Float16
      intermed_df: Float16
      ublock_order: r
      buf_size_mb: 24
      math_fidelity: HiFi4
      t: 36
      mblock: [2, 1]
      ublock: [1, 6]
    op0:
      type: matmul
      grid_loc: [6, 2]
      grid_size: [3, 2]
      inputs: [feeder0, feeder1]
      in_df: [Float16, Float16]
      acc_df: Float16
      out_df: Float16
      intermed_df: Float16
      ublock_order: r
      buf_size_mb: 1
      math_fidelity: HiFi4
      attributes: {m_k: 6, u_kt: 1}
      untilize_output: false
      t: 18
      mblock: [2, 6]
      ublock: [3, 2]
      input_0_tms: [vslice: 3, hslice: 6]
      input_1_tms: [broadcast: {r: 3}, hstack: 2]
    op1:
      type: matmul
      grid_loc: [6, 4]
      grid_size: [3, 2]
      inputs: [feeder0, feeder1]
      in_df: [Float16, Float16]
      acc_df: Float16
      out_df: Float16
      intermed_df: Float16
      ublock_order: r
      buf_size_mb: 1
      math_fidelity: HiFi4
      attributes: {m_k: 18, u_kt: 2}
      untilize_output: false
      t: 36
      mblock: [6, 1]
      ublock: [1, 6]
      input_0_tms: [broadcast: {z: 12}, vslice: 3]
      input_1_tms: [broadcast: {r: 2}, broadcast: {r: 9}]

programs:
  - test_multi_tm_datacopy_matmul_program:
    - param: [$p_microbatch_count, $p_microbatch_size]
    - staticvar: [$lptr, $gptr]
    - var: {$c_zero: 0, $c_wrap: 2}                         # c_wrap = 2 - finally need to be equal to 2*entries == 2*microbatch_size*microbatch_count
    - varinst: [$c_wrap, mul, $c_wrap, $p_microbatch_size]  # c_wrap = 2*microbatch_size
    - varinst: [$c_wrap, mul, $c_wrap, $p_microbatch_count] # c_wrap = 2*microbatch_size*microbatch_count
    - loop: $p_microbatch_count #loop over number of microbatches that make a minibatch
    -   execute: {
          graph_name: test_multi_tm_datacopy_matmul,
          queue_settings: {
            input0_dram: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},
            input1_dram: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr}
          }
        }
    -   varinst: [$lptr, incwrap, $p_microbatch_size, $c_wrap]
    -   varinst: [$gptr, incwrap, $p_microbatch_size, $c_wrap]
    - endloop

test-config:
  test-args:
    microbatch_count: 1 # entries / input_count
    microbatch_size: 2 # input_count
    minibatch_count: 1 # host loop iterations

```

</details>

Repro command: `ARCH_NAME=wormhole_b0 ./build/test/verif/graph_tests/test_graph --silicon --netlist <path-to-netlist> --pipegen2`

fyi @mrakitaTT @rpavlovicTT  @kmitrovicTT
